development:
  adapter: postgresql
  encoding: utf8
  database: uni_bd_2015_development
  pool: 5
  username: hisa
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: uni_bd_2015_test
  pool: 5
  username: hisa
  password: 